image: dotnetimages/microsoft-dotnet-core-sdk-nodejs:6.0_17.x

stages:
  - build
  - test
  - package

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  needs: ["build"]
  script:
    - dotnet test

create_image:
  image: docker:latest
  stage: package
  needs: ["test"]
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
        tag=""
        echo "Running on default branch '$CI_COMMIT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"
  only:
    - main
    - develop