#Create web server and database
services:
    #Create and name a web container through Dockerfile 
    inventory-tracker-web:
      container_name: inventory-tracker-web #Assign a custom name to this container
      image: registry.gitlab.cleft.fun/hunter/inventory-tracker-project:develop #Take this web server image
      ports:
        - 6000:80
      restart: unless-stopped
    #Create a database container through mongo
    database:
      container_name: mongo
      image: mongo #Take this database image from mongo
      restart: unless-stopped