apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: inventory-tracker-web
  name: inventory-tracker-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: inventory-tracker-web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: inventory-tracker-web
    spec:
      containers:
        - image: inventory-tracker-web:develop
          name: inventory-tracker-web
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
